spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8005
zuul:
  routes:
    users:
      path: /user-api/**
      serviceId: user-provider

